import { useEffect, useRef, useState, type FormEvent } from 'react';
import { motion, MotionConfig } from 'motion/react';
import * as Dialog from '@radix-ui/react-dialog';
import { ArrowRight, ArrowUpRight, Bell, BookOpen, CalendarDays, Check, CheckCheck, ChevronDown, ChevronRight, Coins, Download, FileText, FolderOpen, GraduationCap, Heart, LayoutDashboard, LockKeyhole, Menu, MessageCircle, Plus, Send, ShieldCheck, Sparkles, Sprout, Users, X } from 'lucide-react';
import Island from './Island';

type Tab = 'board' | 'funds' | 'chat' | 'docs' | 'calendar';
type Announcement = { id: number; category: string; date: string; title: string; text: string; author: string; role: string; icon: string };
type Doc = { name: string; size: string; url?: string };
const tabs = [{ id: 'board', label: 'Tablica klasy', icon: LayoutDashboard }, { id: 'funds', label: 'Składki', icon: Coins }, { id: 'chat', label: 'Rozmowy rodziców', icon: MessageCircle }, { id: 'docs', label: 'Dokumenty', icon: FolderOpen }, { id: 'calendar', label: 'Kalendarz', icon: CalendarDays }] as const;
const events = [{ day: '15', month: 'WRZ', title: 'Zebranie z rodzicami', detail: '17:00 · Sala 24', parent: true }, { day: '25', month: 'WRZ', title: 'Centrum Nauki Kopernik', detail: '8:15 · Zbiórka przed szkołą', parent: false }, { day: '30', month: 'WRZ', title: 'Dzień Chłopaka', detail: 'Wspólne świętowanie w klasie', parent: false }];
function Logo() { return <a className="logo" href="#" aria-label="KlasCraft — strona główna"><img src="/favicon.svg" alt="" width="35" height="35"/>Klas<span>Craft</span><span className="logo-dot">.</span></a>; }
function App() {
  const [menu, setMenu] = useState(false), [modal, setModal] = useState(false);
  const [role, setRole] = useState<'parent' | 'student'>('parent');
  const [tab, setTab] = useState<Tab>('board');
  const [className, setClassName] = useState('Klasa 4B'), [school, setSchool] = useState('Szkoła Podstawowa nr 12');
  const [announcements, setAnnouncements] = useState<Announcement[]>([]), [loadError, setLoadError] = useState(false);
  const [reload, setReload] = useState(0);
  const [read, setRead] = useState<number[]>([]);
  const [message, setMessage] = useState(''), [messages, setMessages] = useState<string[]>([]);
  const [docs, setDocs] = useState<Doc[]>([{ name: 'Lista rzeczy na wycieczkę.txt', size: '1 KB' }, { name: 'Plan lekcji — wrzesień.txt', size: '1 KB' }]);
  const [notice, setNotice] = useState('');
  const fileInput = useRef<HTMLInputElement>(null), urls = useRef<string[]>([]);
  useEffect(() => { const controller = new AbortController(); setLoadError(false); void fetch('/api/demo/announcements', { signal: controller.signal }).then(r => { if (!r.ok) throw new Error('API'); return r.json() as Promise<Announcement[]>; }).then(setAnnouncements).catch(e => { if (e.name !== 'AbortError') setLoadError(true); }); return () => controller.abort(); }, [reload]);
  useEffect(() => () => urls.current.forEach(URL.revokeObjectURL), []);
  useEffect(() => { if (!notice) return; const timer = setTimeout(() => setNotice(''), 4500); return () => clearTimeout(timer); }, [notice]);
  const selectRole = (next: 'parent' | 'student') => { setRole(next); if (next === 'student' && (tab === 'chat' || tab === 'funds')) setTab('board'); };
  const demo = () => { setMenu(false); document.getElementById('demo')?.scrollIntoView({ behavior: 'smooth' }); };
  const createClass = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); setClassName(String(data.get('class')).trim()); setSchool(String(data.get('school')).trim()); selectRole('parent'); setModal(false); setNotice('Twoja klasa jest gotowa w podglądzie demo.'); demo(); };
  const download = (doc: Doc) => { const url = doc.url ?? URL.createObjectURL(new Blob([doc.name.includes('Plan') ? 'DEMO — KlasCraft\nPoniedziałek: 8:00 Matematyka, 8:55 Język polski, 9:50 Przyroda\nWtorek: 8:00 Język angielski, 8:55 Matematyka, 9:50 WF' : 'DEMO — KlasCraft\nWycieczka 25 września\nZbiórka: 8:15 przed szkołą\nZabierz: drugie śniadanie, wodę, wygodne buty i kurtkę.'], { type: 'text/plain;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = doc.name; a.click(); if (!doc.url) setTimeout(() => URL.revokeObjectURL(url), 1000); };
  return <MotionConfig reducedMotion="user"><a className="skip" href="#main">Przejdź do treści</a>
    <header className="header"><div className="container nav"><Logo/><nav aria-label="Nawigacja główna" className={menu ? 'nav-links open' : 'nav-links'}><a href="#mozliwosci" onClick={() => setMenu(false)}>Możliwości</a><a href="#jak-to-dziala" onClick={() => setMenu(false)}>Jak to działa</a><a href="#dla-kogo" onClick={() => setMenu(false)}>Dla rodziców i uczniów</a></nav><div className="nav-actions"><button className="login" onClick={demo}>Zajrzyj do klasy <ArrowUpRight size={15}/></button><button className="button small" onClick={() => setModal(true)}>Stwórz klasę <Plus size={16}/></button><button className="menu-button icon-button" onClick={() => setMenu(!menu)} aria-label={menu ? 'Zamknij menu' : 'Otwórz menu'} aria-expanded={menu}>{menu ? <X/> : <Menu/>}</button></div></div></header>
    <main id="main">
      <section className="hero container"><motion.div className="hero-copy" initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .65 }}><div className="eyebrow"><span className="tiny-block"/> WSPÓLNA KLASA. WSPÓLNY ŚWIAT.</div><h1>Dobra klasa<br/>zaczyna się od<br/><span>współpracy<span className="pixel-period">.</span></span></h1><p>Mniej zagubionych wiadomości. Więcej bycia razem.<br className="desktop-break"/> Składki, rozmowy i szkolne sprawy — w jednym miejscu,<br className="desktop-break"/> które łączy rodziców i uczniów.</p><div className="hero-buttons"><button className="button" onClick={() => setModal(true)}>Zbuduj swoją klasę <ArrowRight size={18}/></button><button className="button secondary" onClick={demo}><LayoutDashboard size={17}/> Zobacz, jak to działa</button></div><div className="hero-note"><span className="mini-avatars"><i>MK</i><i>AK</i><i>PW</i></span><span>Małe sprawy. Wielka <strong>wspólnota.</strong><br/><span className="note-sub">Zaprojektowane z myślą o szkolnej codzienności.</span></span></div></motion.div>
        <motion.div className="hero-art" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: .9 }}><div className="art-grid"/><div className="art-orbit"/><span className="art-caption">TWÓJ MAŁY, WSPÓLNY ŚWIAT</span><Island/><div className="floating-card float-message"><span className="floating-icon"><MessageCircle size={20}/></span><div><strong>Wszyscy na bieżąco</strong><small>Jedna klasa, dobra komunikacja</small></div><span className="online-dot"/></div><div className="floating-card float-fund"><span className="floating-icon gold"><Coins size={20}/></span><div><strong>Cel osiągnięty!</strong><small>Razem możemy więcej <span>✦</span></small></div><span className="check-square"><Check size={13}/></span></div><div className="world-label"><span/> ŚWIAT KLASY: POŁĄCZONY</div></motion.div>
      </section>
      <div className="benefit-bar container"><span><ShieldCheck/> Przestrzeń tylko dla Was</span><span><Users/> Rodzice i uczniowie razem</span><span><Sprout/> Mniej chaosu, więcej spokoju</span><span><Heart/> Zbudowane dla społeczności</span></div>
      <section id="mozliwosci" className="features section container"><div className="section-heading"><div><div className="eyebrow">EKWIPUNEK DOBRZE ZORGANIZOWANEJ KLASY</div><h2>Wszystko na swoim <span>miejscu.</span></h2></div><p>Każda sprawa ma swój klocek.<br/>Razem tworzą coś naprawdę dobrego.</p></div><div className="feature-grid">{[{ icon: Coins, title: 'Składki bez zagadek', text: 'Jasny cel, kwota i postęp zbiórki. Każdy rodzic wie, co jest już załatwione.', color: 'gold', tag: 'WSZYSTKO SIĘ ZGADZA', tab: 'funds' }, { icon: MessageCircle, title: 'Rozmowy z sensem', text: 'Ustalenia, pomysły i szybkie pytania. Osobna przestrzeń do rozmów rodziców.', color: 'green', tag: 'DOBRZE BYĆ W KONTAKCIE', tab: 'chat' }, { icon: FolderOpen, title: 'Dokumenty pod ręką', text: 'Zgody, listy i ważne załączniki. Koniec szukania plików w historii czatu.', color: 'blue', tag: 'ZNAJDZIESZ W CHWILĘ', tab: 'docs' }, { icon: Bell, title: 'Nic Was nie ominie', text: 'Aktualności i terminy w jednym miejscu. Sprawy klasy zawsze na bieżąco.', color: 'coral', tag: 'WIESZ, CO W KLASIE PISZCZY', tab: 'board' }].map((f, i) => <motion.button key={f.title} className={`feature-card ${f.color}`} initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * .07 }} onClick={() => { selectRole('parent'); setTab(f.tab as Tab); demo(); }}><div className={`feature-icon ${f.color}`}><f.icon size={27}/><span/></div><h3>{f.title}</h3><p>{f.text}</p><div className="feature-bottom"><span>{f.tag}</span><ArrowUpRight size={17}/></div></motion.button>)}</div></section>
      <section id="demo" className="demo-section"><div className="container"><div className="demo-heading"><div><div className="eyebrow"><span className="tiny-block"/> TWOJA KLASA, TYLKO LEPIEJ ZORGANIZOWANA</div><h2>Wejdź. Rozejrzyj się. <span>Poczuj spokój.</span></h2><p>Tak może wyglądać Wasza codzienność. Wypróbuj interaktywne demo.</p></div><div className="role-switch" aria-label="Wybierz widok demo"><button aria-pressed={role === 'parent'} className={role === 'parent' ? 'active' : ''} onClick={() => selectRole('parent')}><Users size={16}/> Rodzic</button><button aria-pressed={role === 'student'} className={role === 'student' ? 'active' : ''} onClick={() => selectRole('student')}><GraduationCap size={18}/> Uczeń</button></div></div>
      <div className="app-preview"><aside className="app-sidebar"><Logo/><div className="class-selector"><span className="class-icon">4B</span><div><strong>{className}</strong><small>Rok szkolny 2026/27</small></div><ChevronDown size={14}/></div><span className="sidebar-label">NASZA PRZESTRZEŃ</span><nav aria-label="Panel klasy">{tabs.filter(t => role === 'parent' || !['chat', 'funds'].includes(t.id)).map(t => <button key={t.id} className={tab === t.id ? 'selected' : ''} onClick={() => setTab(t.id)}><t.icon size={18}/>{t.label}{t.id === 'board' && <span className="nav-count">2</span>}{t.id === 'chat' && <span className="unread-dot"/>}</button>)}</nav><div className="sidebar-bottom"><div className="level-mark"><Sprout size={24}/></div><strong>Razem rośniemy.</strong><p>Każdy mały krok buduje<br/>naszą klasową społeczność.</p><div className="sidebar-user"><span className={`avatar ${role === 'student' ? 'purple' : ''}`}>{role === 'parent' ? 'MK' : 'AK'}</span><div><strong>{role === 'parent' ? 'Marta Kowalska' : 'Ala Kowalska'}</strong><small>{role === 'parent' ? 'Rodzic' : 'Uczeń'} · konto demo</small></div></div></div></aside>
      <div className="app-main"><div className="app-topline"><span>{school} <ChevronRight size={13}/> <strong>{className}</strong></span><span className="demo-badge">WERSJA DEMO</span></div><div className="app-body"><div className="dashboard-heading"><div><h3>{tab === 'board' ? `Cześć, ${role === 'parent' ? 'Marto' : 'Alu'}!` : tabs.find(t => t.id === tab)?.label} <span>{tab === 'board' ? '✦' : ''}</span></h3><p>{tab === 'board' ? 'Dobrze Cię widzieć. Oto co słychać w Twojej klasie.' : 'Wspólne sprawy klasy, uporządkowane w jednym miejscu.'}</p></div><span className="today"><CalendarDays size={14}/> 8 września 2026</span></div>
      {tab === 'board' && <><div className="stat-grid"><button onClick={() => document.getElementById('announcements')?.scrollIntoView({ behavior: 'smooth', block: 'center' })}><span className="stat-icon green"><Bell size={18}/></span><div><small>Nowe ogłoszenia</small><strong>2 <span>na bieżąco</span></strong></div><ArrowUpRight size={16}/></button><button onClick={() => setTab(role === 'parent' ? 'funds' : 'docs')}><span className="stat-icon gold">{role === 'parent' ? <Coins size={18}/> : <FolderOpen size={18}/>}</span><div><small>{role === 'parent' ? 'Aktywne składki' : 'Dokumenty klasy'}</small><strong>2 <span>{role === 'parent' ? 'wspólne cele' : 'do pobrania'}</span></strong></div><ArrowUpRight size={16}/></button><button onClick={() => setTab('calendar')}><span className="stat-icon blue"><CalendarDays size={18}/></span><div><small>Najbliższe wydarzenie</small><strong>{role === 'parent' ? '15' : '25'} <span>września</span></strong></div><ArrowUpRight size={16}/></button></div><div className="dashboard-columns"><div id="announcements"><div className="panel-heading"><h4>Na tablicy klasy</h4><span>OSTATNIE OGŁOSZENIA</span></div>{loadError ? <div className="announcement">Nie udało się pobrać ogłoszeń. <button className="text-button" onClick={() => setReload(reload + 1)}>Spróbuj ponownie</button></div> : announcements.length === 0 ? <p role="status">Wczytuję ogłoszenia…</p> : announcements.map(a => <article className="announcement" key={a.id}><div className="announcement-meta"><span className={a.icon === 'trip' ? 'tag green' : 'tag gold'}>{a.category}</span><small>{a.date}</small></div><h4>{a.title}</h4><p>{a.text}</p><div className="announcement-footer"><span className="avatar small-avatar">AK</span><span><strong>{a.author}</strong><small>{a.role}</small></span><button className={read.includes(a.id) ? 'read-button is-read' : 'read-button'} onClick={() => setRead(prev => prev.includes(a.id) ? prev.filter(id => id !== a.id) : [...prev, a.id])} aria-pressed={read.includes(a.id)}>{read.includes(a.id) ? <CheckCheck size={16}/> : <Check size={16}/>} {read.includes(a.id) ? 'Przeczytane' : 'Oznacz jako przeczytane'}</button></div></article>)}</div><aside className="dashboard-right"><div className="panel-heading"><h4>Tuż za rogiem</h4><CalendarDays size={16}/></div><div className="event-list">{events.filter(e => role === 'parent' || !e.parent).map(e => <div className="event" key={e.day}><div className="date-tile"><strong>{e.day}</strong><small>{e.month}</small></div><div><strong>{e.title}</strong><small>{e.detail}</small></div></div>)}<button className="text-button" onClick={() => setTab('calendar')}>Zobacz kalendarz <ArrowRight size={13}/></button></div><div className="class-goal"><div><Sprout size={21}/><span>NASZ WSPÓLNY CEL</span></div><h4>Małe kroki.<br/>Wielkie przygody.</h4><p>Budujemy klasę, w której<br/>każdy czuje się u siebie.</p><div className="pixel-garden">▟ ▄ ▙ ▄ ▟ ▄</div></div></aside></div></>}
      {tab === 'funds' && role === 'parent' && <div className="funds-view"><div className="inline-notice"><Coins size={17}/> Przykładowe zbiórki — demo nie przyjmuje płatności.</div>{[{ title: 'Wycieczka do Centrum Nauki Kopernik', amount: 1800, target: 2400, each: 100, people: 18 }, { title: 'Klasowy fundusz na dobry początek', amount: 960, target: 1200, each: 50, people: 19 }].map(f => <article className="fund-card" key={f.title}><span className="feature-icon gold"><Coins/></span><div><span className="tag green">ZBIÓRKA TRWA</span><h4>{f.title}</h4><p>{f.people} wpłat · cel: {f.target.toLocaleString('pl-PL')} zł</p><div className="progress" role="progressbar" aria-label={f.title} aria-valuenow={f.amount} aria-valuemin={0} aria-valuemax={f.target}><span style={{ width: `${f.amount / f.target * 100}%` }}/></div><div className="fund-numbers"><strong>{f.amount.toLocaleString('pl-PL')} zł zebrano</strong><span>{f.each} zł / uczeń</span></div></div></article>)}</div>}
      {tab === 'chat' && role === 'parent' && <div className="chat-view"><div className="inline-notice"><LockKeyhole size={16}/> Rozmowy rodziców · fikcyjna rozmowa demonstracyjna</div><div className="chat-messages" aria-live="polite"><div className="chat-bubble"><strong>Piotr Wiśniewski <small>10:24</small></strong><p>Cześć! Czy na wycieczkę dzieci zabierają własny prowiant?</p></div><div className="chat-bubble"><strong>Anna Kowalska <small>10:28</small></strong><p>Tak, proszę spakować drugie śniadanie i wodę. Listę rzeczy dodałam do dokumentów. 😊</p></div>{messages.map((m, i) => <div className="chat-bubble mine" key={i}><strong>Ty <small>teraz · demo</small></strong><p>{m}</p></div>)}</div><form className="message-form" onSubmit={e => { e.preventDefault(); if (message.trim()) { setMessages([...messages, message.trim()]); setMessage(''); } }}><input aria-label="Wiadomość do rodziców" value={message} onChange={e => setMessage(e.target.value)} maxLength={2000} placeholder="Napisz coś do rodziców…"/><button className="button small" disabled={!message.trim()} aria-label="Wyślij wiadomość demonstracyjną"><Send size={17}/></button></form><small className="demo-explanation">Wiadomości pozostają w tym podglądzie i nie są wysyłane do innych osób.</small></div>}
      {tab === 'docs' && <div className="documents-view"><div className="documents-toolbar"><p>Ważne pliki, zawsze w jednym miejscu.</p>{role === 'parent' && <button className="button small" onClick={() => fileInput.current?.click()}><Plus size={15}/> Dodaj dokument</button>}<input ref={fileInput} type="file" hidden accept=".pdf,.doc,.docx,.txt,.png,.jpg,.jpeg" onChange={e => { const file = e.target.files?.[0]; if (!file) return; if (file.size > 10 * 1024 * 1024) { setNotice('Plik jest za duży. Maksymalny rozmiar to 10 MB.'); e.target.value = ''; return; } const url = URL.createObjectURL(file); urls.current.push(url); setDocs([...docs, { name: file.name, size: `${Math.max(1, Math.round(file.size / 1024))} KB`, url }]); setNotice('Dokument dodany do lokalnego podglądu.'); e.target.value = ''; }}/></div>{docs.map((doc, i) => <div className="document-row" key={i}><span className="stat-icon blue"><FileText size={21}/></span><div><strong>{doc.name}</strong><small>{doc.size} · Widoczny dla całej klasy</small></div><button className="icon-button" aria-label={`Pobierz ${doc.name}`} onClick={() => download(doc)}><Download size={19}/></button></div>)}<p className="demo-explanation">Załączniki demo są dostępne tylko w tej karcie, do jej odświeżenia. Maksymalny rozmiar: 10 MB.</p></div>}
      {tab === 'calendar' && <div className="calendar-view"><div className="calendar-title"><h4>Wrzesień 2026</h4><span className="tag green">PLAN KLASY</span></div>{events.filter(e => role === 'parent' || !e.parent).map(e => <article className="calendar-event" key={e.day}><div className="date-tile"><strong>{e.day}</strong><small>{e.month}</small></div><div><h4>{e.title}</h4><p>{e.detail}</p></div><span className="tag">{e.parent ? 'Dla rodziców' : 'Dla wszystkich'}</span></article>)}</div>}
      </div><div className="app-status"><span><span className="online-dot"/> Twoje miejsce w klasie</span><span><LockKeyhole size={12}/> {role === 'parent' ? 'Widok rodzica' : 'Widok ucznia · bez rozmów rodziców'}</span></div></div></div><p className="preview-caption"><Sparkles size={14}/> To przestrzeń demonstracyjna z przykładowymi danymi. Klikaj śmiało — jesteś u siebie.</p></div></section>
      <section id="dla-kogo" className="audience section container"><div className="audience-copy"><div className="eyebrow">JEDNA KLASA. RÓŻNE PERSPEKTYWY.</div><h2>Wspólny świat.<br/><span>Własna przestrzeń.</span></h2><p>Rodzice ogarniają organizację. Uczniowie wiedzą, co się dzieje. Każdy widzi to, czego potrzebuje — i czuje się częścią klasy.</p><a href="#demo" className="text-button">Sprawdź oba widoki <ArrowRight size={16}/></a></div><div className="audience-cards"><article><span className="feature-icon green"><Users/></span><h3>Dla rodziców</h3><p>Spokojna głowa. Wspólne decyzje.</p><ul><li><Check/> Aktualności i kalendarz klasy</li><li><Check/> Składki i postępy zbiórek</li><li><Check/> Prywatne rozmowy rodziców</li><li><Check/> Dodawanie dokumentów</li></ul><button className="text-button" onClick={() => { selectRole('parent'); setTab('board'); demo(); }}>Zobacz widok rodzica <ArrowUpRight size={15}/></button></article><article className="student-card"><span className="feature-icon gold"><GraduationCap/></span><h3>Dla uczniów</h3><p>W centrum klasowych wydarzeń.</p><ul><li><Check/> Aktualności i kalendarz klasy</li><li><Check/> Ważne informacje i ogłoszenia</li><li><Check/> Dokumenty do pobrania</li><li className="muted"><LockKeyhole/> Bez czatu rodziców i składek</li></ul><button className="text-button" onClick={() => { selectRole('student'); setTab('board'); demo(); }}>Zobacz widok ucznia <ArrowUpRight size={15}/></button></article></div></section>
      <section id="jak-to-dziala" className="how-section container"><div className="section-heading"><div><div className="eyebrow">PIERWSZY KLOCEK JEST NAJPROSTSZY</div><h2>Dobry początek w <span>trzech krokach.</span></h2></div><BookOpen size={32}/></div><div className="steps">{[{ n: '01', title: 'Stwórz przestrzeń', text: 'Nadaj klasie nazwę i zobacz, jak wygląda Wasze miejsce.' }, { n: '02', title: 'Poznaj oba widoki', text: 'Przełącz rodzica i ucznia. Odkryj przestrzeń dla każdego.' }, { n: '03', title: 'Wypróbuj możliwości', text: 'Dodaj plik, napisz wiadomość i sprawdź klasową tablicę.' }].map(s => <div className="step" key={s.n}><span>{s.n}</span><div><h3>{s.title}</h3><p>{s.text}</p></div></div>)}</div></section>
      <section className="cta container"><div className="cta-pixels" aria-hidden="true">▟<br/>▟▙<br/>▟▙▟</div><div><div className="eyebrow">RAZEM BUDUJE SIĘ LEPIEJ</div><h2>Wasza klasa. Wasz mały świat.</h2><p>Zróbcie miejsce na dobrą komunikację.</p></div><button className="button cream" onClick={() => setModal(true)}>Postaw pierwszy klocek <ArrowRight size={18}/></button></section>
    </main><footer className="footer container"><Logo/><p>Małe klocki. Wielkie możliwości.</p><span>© 2026 KlasCraft <span className="footer-separator">·</span> Niezależny projekt, niezwiązany z Mojang.</span></footer>
    <Dialog.Root open={modal} onOpenChange={setModal}><Dialog.Portal><Dialog.Overlay className="modal-overlay"/><Dialog.Content className="modal-content"><Dialog.Close className="modal-close icon-button" aria-label="Zamknij"><X size={20}/></Dialog.Close><span className="feature-icon green"><Sprout size={26}/></span><Dialog.Title>Postaw pierwszy klocek.</Dialog.Title><Dialog.Description>Spersonalizuj podgląd swojej klasy. To demo — nie zakładamy jeszcze prawdziwego konta.</Dialog.Description><form onSubmit={createClass}><label>Nazwa klasy<input name="class" placeholder="np. Klasa 4B" required maxLength={35} pattern=".*\S.*" defaultValue={className}/></label><label>Nazwa szkoły<input name="school" placeholder="np. Szkoła Podstawowa nr 12" required maxLength={70} pattern=".*\S.*" defaultValue={school}/></label><button className="button" type="submit">Otwórz moją klasę w demo <ArrowRight size={17}/></button></form><small><LockKeyhole size={13}/> Dane pozostają w tej sesji przeglądarki.</small></Dialog.Content></Dialog.Portal></Dialog.Root>
    {notice && <div className="toast" role="status"><Check size={18}/>{notice}<button className="icon-button" aria-label="Zamknij powiadomienie" onClick={() => setNotice('')}><X size={15}/></button></div>}
  </MotionConfig>;
}
export default App;
